branch-defaults:
  main:
    environment: Pictures-704-dev
    group_suffix: null
global:
  application_name: Pictures_7.0.4
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
