version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
 test:
   working_directory: ~/code
   docker:
     - image: cimg/ruby:3.0.4
   steps:
     - checkout
     - run:
         command: ruby --version
     - run:
         command: bundle install
    #  - run:
    #      command: rails test

 deploy-gcp:
   working_directory: ~/code
   executor: gcp-cli/default
   parameters:
      google-project-id:
        type: env_var_name
        default: GOOGLE_PROJECT_ID
      gcloud-service-key:
        type: env_var_name
        default: GCLOUD_SERVICE_KEY
   steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize:
          google-project-id: << parameters.google-project-id >>
          gcloud-service-key: << parameters.gcloud-service-key >>
      - run:
          name: Deploy to Cloud Build Production
          command: |
            gcloud builds submit --async --config=cloudbuild.yaml .


workflows:
 version: 2.1
 build-test-and-deploy:
   jobs:
     - test
     - deploy-gcp:
         requires:
           - test
         filters:
            branches:
              only:
                - GCP-Deployment
